export const FETCH_POKEMONS_LIST = 'FETCH_POKEMONS_LIST';
export const FETCH_POKEMON_DETAIL = 'FETCH_POKEMON_DETAIL';
export const FETCH_MY_POKEMONS = 'FETCH_MY_POKEMONS';
export const CATCH_POKEMON = 'CATCH_POKEMON';
export const RELEASE_MY_POKEMON = 'RELEASE_MY_POKEMON';
export const SET_CURRENT_POKEMONS_LIST_PAGE = 'SET_CURRENT_POKEMONS_LIST_PAGE';
export const SET_CURRENT_MY_POKEMONS_LIST_PAGE = 'SET_CURRENT_MY_POKEMONS_LIST_PAGE';
export const SET_SELECTED_BOTTOM_ACTION = 'SET_SELECTED_BOTTOM_ACTION';